name: good_enums
description: Good enum code generation
version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  build:
  source_gen:
  good_enums_annotations:
    path: ../good_enums_annotations

dev_dependencies:
  build_test:
  build_runner:
  test: ^1.0.0
