name: good_enums
description: Good enum code generation
version: 0.2.0
repository: https://github.com/MattiaPispisa/good_enums/tree/main/packages/good_enums

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^5.2.0
  build: ^2.0.0
  source_gen: ^1.0.0
  good_enums_annotations: ^0.2.0

dev_dependencies:
  build_runner: ^2.0.0
