name: good_enums_annotations
description: Good enum annotations
version: 0.1.1
repository: https://github.com/MattiaPispisa/good_enums/tree/main/packages/good_enums_annotations

environment:
  sdk: ">=2.17.0 <3.0.0"

